version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FSharp.Data
    versions:
    - 4.0.0
    - 4.0.1
    - 4.1.0
  - dependency-name: FSharp.Core
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: CurrieTechnologies.Razor.Clipboard
    versions:
    - 1.3.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
